// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    FilterComponent: typeof import('./src/components/FilterComponent.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ResultCard: typeof import('./src/components/ResultCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
